ERROR 2021-05-15 06:47:32,579 log 10846 139756512167680 Internal Server Error: /
Traceback (most recent call last):
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mechanic/dev/QuickPortfolio/projects/views.py", line 24, in Home
    return render(request, template_name, context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2021-05-15 07:27:04,288 log 14379 140492714886912 Internal Server Error: /
Traceback (most recent call last):
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mechanic/dev/QuickPortfolio/projects/views.py", line 40, in Home
    return render(request, template_name, context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'portfolio_detail' not found. 'portfolio_detail' is not a valid view function or pattern name.
ERROR 2021-05-15 07:27:25,808 log 14429 139739877988096 Internal Server Error: /
Traceback (most recent call last):
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mechanic/dev/QuickPortfolio/projects/views.py", line 40, in Home
    return render(request, template_name, context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'portfolio_detail' not found. 'portfolio_detail' is not a valid view function or pattern name.
ERROR 2021-05-15 07:35:27,345 log 14746 139855981696768 Internal Server Error: /
Traceback (most recent call last):
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mechanic/dev/QuickPortfolio/projects/views.py", line 40, in Home
    return render(request, template_name, context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'portfolio_detail' not found. 'portfolio_detail' is not a valid view function or pattern name.
ERROR 2021-05-15 07:35:37,546 log 14790 140633230923520 Internal Server Error: /
Traceback (most recent call last):
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mechanic/dev/QuickPortfolio/projects/views.py", line 40, in Home
    return render(request, template_name, context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'portfolio_detail' not found. 'portfolio_detail' is not a valid view function or pattern name.
ERROR 2021-05-15 07:37:06,291 log 14790 140633230923520 Internal Server Error: /
Traceback (most recent call last):
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mechanic/dev/QuickPortfolio/projects/views.py", line 40, in Home
    return render(request, template_name, context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/mechanic/dev/QuickPortfolio/env/lib/python3.7/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'portfolio_detail' not found. 'portfolio_detail' is not a valid view function or pattern name.
